services:
  db:
    image: postgres:16
    volumes:
      - octoscrapper_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - "5432:5432"
  backend:
    image: ruby:3.4
    volumes:
      - ./backend:/app
    env_file:
      .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: bash
volumes:
  octoscrapper_data:
