source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "redis"
gem "sidekiq"
gem "sidekiq-scheduler"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "kamal", require: false
gem "nokogiri"
gem "faraday"
gem "rack-cors"
gem "thruster", require: false
gem "tinyurl_shortener"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
end
